### ISSUE TITLE
Crashes when running hephaestus.xml when no device is on the network

### ISSUE THREAD

**Issue by keionbis** [Halloween2020TheChild/GroguMechanicsCad#1]
There is no fall back for when there is no device on the network so this cannot just be run in sim. If this sounds like a local system issue let me know @madhephaestus

**Comment by madhephaestus** [comment]
yeah, i didnt test for that, let me fix it...

**Comment by madhephaestus** [comment]
Close BowlerStudio and restart it to get the changes
